// Top ~250 global tickers for instant CommandPalette filtering.
// Covers S&P 500 core, high-profile growth, and major international ADRs.
// Filtered locally (0ms) before falling back to API search for unknowns.
export const TOP_TICKERS = [
  // ── US Mega / Large Cap ────────────────────────────────────────────
  { ticker: 'AAPL',  name: 'Apple' },
  { ticker: 'MSFT',  name: 'Microsoft' },
  { ticker: 'NVDA',  name: 'NVIDIA' },
  { ticker: 'AMZN',  name: 'Amazon' },
  { ticker: 'GOOGL', name: 'Alphabet' },
  { ticker: 'GOOG',  name: 'Alphabet (C)' },
  { ticker: 'META',  name: 'Meta Platforms' },
  { ticker: 'TSLA',  name: 'Tesla' },
  { ticker: 'LLY',   name: 'Eli Lilly' },
  { ticker: 'AVGO',  name: 'Broadcom' },
  { ticker: 'JPM',   name: 'JPMorgan Chase' },
  { ticker: 'XOM',   name: 'ExxonMobil' },
  { ticker: 'V',     name: 'Visa' },
  { ticker: 'MA',    name: 'Mastercard' },
  { ticker: 'UNH',   name: 'UnitedHealth' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson' },
  { ticker: 'PG',    name: 'Procter & Gamble' },
  { ticker: 'HD',    name: 'Home Depot' },
  { ticker: 'COST',  name: 'Costco' },
  { ticker: 'MRK',   name: 'Merck' },
  { ticker: 'ABBV',  name: 'AbbVie' },
  { ticker: 'CVX',   name: 'Chevron' },
  { ticker: 'ORCL',  name: 'Oracle' },
  { ticker: 'BAC',   name: 'Bank of America' },
  { ticker: 'WMT',   name: 'Walmart' },
  { ticker: 'NFLX',  name: 'Netflix' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices' },
  { ticker: 'KO',    name: 'Coca-Cola' },
  { ticker: 'PEP',   name: 'PepsiCo' },
  { ticker: 'ADBE',  name: 'Adobe' },
  { ticker: 'CSCO',  name: 'Cisco' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific' },
  { ticker: 'ACN',   name: 'Accenture' },
  { ticker: 'MCD',   name: "McDonald's" },
  { ticker: 'CRM',   name: 'Salesforce' },
  { ticker: 'QCOM',  name: 'Qualcomm' },
  { ticker: 'IBM',   name: 'IBM' },
  { ticker: 'GE',    name: 'GE Aerospace' },
  { ticker: 'CAT',   name: 'Caterpillar' },
  { ticker: 'AXP',   name: 'American Express' },
  { ticker: 'SPGI',  name: 'S&P Global' },
  { ticker: 'GS',    name: 'Goldman Sachs' },
  { ticker: 'MS',    name: 'Morgan Stanley' },
  { ticker: 'BLK',   name: 'BlackRock' },
  { ticker: 'LMT',   name: 'Lockheed Martin' },
  { ticker: 'RTX',   name: 'RTX Corporation' },
  { ticker: 'HON',   name: 'Honeywell' },
  { ticker: 'UPS',   name: 'United Parcel Service' },
  { ticker: 'AMGN',  name: 'Amgen' },
  { ticker: 'GILD',  name: 'Gilead Sciences' },
  { ticker: 'T',     name: 'AT&T' },
  { ticker: 'VZ',    name: 'Verizon' },
  { ticker: 'COP',   name: 'ConocoPhillips' },
  { ticker: 'SLB',   name: 'SLB' },
  { ticker: 'NEE',   name: 'NextEra Energy' },
  { ticker: 'WM',    name: 'Waste Management' },
  { ticker: 'MMM',   name: '3M' },
  { ticker: 'INTC',  name: 'Intel' },
  { ticker: 'PFE',   name: 'Pfizer' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb' },
  { ticker: 'CI',    name: 'Cigna' },
  { ticker: 'CVS',   name: 'CVS Health' },
  { ticker: 'MO',    name: 'Altria' },
  { ticker: 'PM',    name: 'Philip Morris International' },
  { ticker: 'MDLZ',  name: 'Mondelez' },
  { ticker: 'LOW',   name: "Lowe's" },
  { ticker: 'TGT',   name: 'Target' },
  { ticker: 'NKE',   name: 'Nike' },
  { ticker: 'SBUX',  name: 'Starbucks' },
  { ticker: 'BA',    name: 'Boeing' },
  { ticker: 'DE',    name: 'John Deere' },
  { ticker: 'DUK',   name: 'Duke Energy' },
  { ticker: 'SO',    name: 'Southern Company' },
  { ticker: 'AEP',   name: 'AEP' },
  { ticker: 'WFC',   name: 'Wells Fargo' },
  { ticker: 'C',     name: 'Citigroup' },
  { ticker: 'USB',   name: 'US Bancorp' },
  { ticker: 'TFC',   name: 'Truist Financial' },
  { ticker: 'SCHW',  name: 'Charles Schwab' },
  { ticker: 'BX',    name: 'Blackstone' },
  { ticker: 'KKR',   name: 'KKR' },
  { ticker: 'APO',   name: 'Apollo Global Management' },
  { ticker: 'ICE',   name: 'Intercontinental Exchange' },
  { ticker: 'CME',   name: 'CME Group' },
  { ticker: 'CBOE',  name: 'Cboe Global Markets' },
  { ticker: 'NDAQ',  name: 'Nasdaq' },
  { ticker: 'MSCI',  name: 'MSCI' },
  { ticker: 'MCO',   name: "Moody's" },
  // ── Technology / Growth ────────────────────────────────────────────
  { ticker: 'UBER',  name: 'Uber' },
  { ticker: 'LYFT',  name: 'Lyft' },
  { ticker: 'SPOT',  name: 'Spotify' },
  { ticker: 'RBLX',  name: 'Roblox' },
  { ticker: 'HOOD',  name: 'Robinhood' },
  { ticker: 'COIN',  name: 'Coinbase' },
  { ticker: 'PLTR',  name: 'Palantir' },
  { ticker: 'RIVN',  name: 'Rivian' },
  { ticker: 'LCID',  name: 'Lucid Group' },
  { ticker: 'AFRM',  name: 'Affirm' },
  { ticker: 'SOFI',  name: 'SoFi Technologies' },
  { ticker: 'DKNG',  name: 'DraftKings' },
  { ticker: 'ABNB',  name: 'Airbnb' },
  { ticker: 'DASH',  name: 'DoorDash' },
  { ticker: 'DOCU',  name: 'DocuSign' },
  { ticker: 'ZM',    name: 'Zoom' },
  { ticker: 'CRWD',  name: 'CrowdStrike' },
  { ticker: 'OKTA',  name: 'Okta' },
  { ticker: 'NET',   name: 'Cloudflare' },
  { ticker: 'DDOG',  name: 'Datadog' },
  { ticker: 'SNOW',  name: 'Snowflake' },
  { ticker: 'MDB',   name: 'MongoDB' },
  { ticker: 'CFLT',  name: 'Confluent' },
  { ticker: 'PATH',  name: 'UiPath' },
  { ticker: 'BILL',  name: 'Bill.com' },
  { ticker: 'HUBS',  name: 'HubSpot' },
  { ticker: 'TEAM',  name: 'Atlassian' },
  { ticker: 'WDAY',  name: 'Workday' },
  { ticker: 'NOW',   name: 'ServiceNow' },
  { ticker: 'PANW',  name: 'Palo Alto Networks' },
  { ticker: 'FTNT',  name: 'Fortinet' },
  { ticker: 'ZS',    name: 'Zscaler' },
  { ticker: 'S',     name: 'SentinelOne' },
  { ticker: 'TWLO',  name: 'Twilio' },
  { ticker: 'SHOP',  name: 'Shopify' },
  { ticker: 'SQ',    name: 'Block' },
  { ticker: 'PYPL',  name: 'PayPal' },
  { ticker: 'ETSY',  name: 'Etsy' },
  { ticker: 'W',     name: 'Wayfair' },
  { ticker: 'EBAY',  name: 'eBay' },
  { ticker: 'TTD',   name: 'The Trade Desk' },
  { ticker: 'PINS',  name: 'Pinterest' },
  { ticker: 'SNAP',  name: 'Snap' },
  { ticker: 'GME',   name: 'GameStop' },
  { ticker: 'AMC',   name: 'AMC Entertainment' },
  { ticker: 'APP',   name: 'AppLovin' },
  { ticker: 'GTLB',  name: 'GitLab' },
  { ticker: 'BRZE',  name: 'Braze' },
  { ticker: 'UI',    name: 'Ubiquiti' },
  // ── Pharma / Biotech ───────────────────────────────────────────────
  { ticker: 'NVO',   name: 'Novo Nordisk' },
  { ticker: 'AZN',   name: 'AstraZeneca' },
  { ticker: 'RHHBY', name: 'Roche' },
  { ticker: 'SNY',   name: 'Sanofi' },
  { ticker: 'GSK',   name: 'GSK' },
  { ticker: 'BIIB',  name: 'Biogen' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals' },
  { ticker: 'REGN',  name: 'Regeneron' },
  { ticker: 'MRNA',  name: 'Moderna' },
  { ticker: 'BNTX',  name: 'BioNTech' },
  { ticker: 'INCY',  name: 'Incyte' },
  { ticker: 'ALNY',  name: 'Alnylam Pharmaceuticals' },
  // ── International ADRs ─────────────────────────────────────────────
  { ticker: 'TSM',   name: 'Taiwan Semiconductor' },
  { ticker: 'BABA',  name: 'Alibaba' },
  { ticker: 'JD',    name: 'JD.com' },
  { ticker: 'PDD',   name: 'PDD Holdings' },
  { ticker: 'BIDU',  name: 'Baidu' },
  { ticker: 'NIO',   name: 'NIO' },
  { ticker: 'XPEV',  name: 'XPeng' },
  { ticker: 'LI',    name: 'Li Auto' },
  { ticker: 'TCEHY', name: 'Tencent' },
  { ticker: 'BILI',  name: 'Bilibili' },
  { ticker: 'SAP',   name: 'SAP' },
  { ticker: 'ASML',  name: 'ASML' },
  { ticker: 'SHEL',  name: 'Shell' },
  { ticker: 'BP',    name: 'BP' },
  { ticker: 'UL',    name: 'Unilever' },
  { ticker: 'TM',    name: 'Toyota' },
  { ticker: 'HMC',   name: 'Honda' },
  { ticker: 'SONY',  name: 'Sony' },
  { ticker: 'RIO',   name: 'Rio Tinto' },
  { ticker: 'BHP',   name: 'BHP' },
  { ticker: 'VALE',  name: 'Vale' },
  { ticker: 'GOLD',  name: 'Barrick Gold' },
  { ticker: 'NEM',   name: 'Newmont' },
  { ticker: 'NVS',   name: 'Novartis' },
  // ── Energy ────────────────────────────────────────────────────────
  { ticker: 'EOG',   name: 'EOG Resources' },
  { ticker: 'PXD',   name: 'Pioneer Natural Resources' },
  { ticker: 'DVN',   name: 'Devon Energy' },
  { ticker: 'MRO',   name: 'Marathon Oil' },
  { ticker: 'OXY',   name: 'Occidental Petroleum' },
  { ticker: 'HAL',   name: 'Halliburton' },
  { ticker: 'VLO',   name: 'Valero Energy' },
  { ticker: 'PSX',   name: 'Phillips 66' },
  { ticker: 'MPC',   name: 'Marathon Petroleum' },
  // ── Consumer / Retail ─────────────────────────────────────────────
  { ticker: 'KR',    name: 'Kroger' },
  { ticker: 'DLTR',  name: 'Dollar Tree' },
  { ticker: 'DG',    name: 'Dollar General' },
  { ticker: 'FIVE',  name: 'Five Below' },
  { ticker: 'ROST',  name: 'Ross Stores' },
  { ticker: 'TJX',   name: 'TJX Companies' },
  { ticker: 'LULU',  name: 'Lululemon' },
  // ── Real Estate / REITs ───────────────────────────────────────────
  { ticker: 'AMT',   name: 'American Tower' },
  { ticker: 'CCI',   name: 'Crown Castle' },
  { ticker: 'PLD',   name: 'Prologis' },
  { ticker: 'O',     name: 'Realty Income' },
  { ticker: 'SPG',   name: 'Simon Property Group' },
];
